In [1]:
# Project 3: Data Cleaning & Preparation
# Framework: Transforming Raw Datasets into Analysis-Ready Assets

In [4]:
import pandas as pd
import numpy as np

print("STEP 1: Simulating Raw Incoming INR Transaction Logs")

raw_inr_data = {
    'InvoiceID': ['INV-001', 'INV-002', 'INV-002', 'INV-004', 'INV-005'],  
    'Amount_Raw': ['₹1,500', 'Rs. 450', 'Rs. 450', '₹-200', '₹3,200'],    
    'PaymentMode': ['UPI', 'upi', 'Net Banking', 'Cash', np.nan],         
    'CustomerCity': ['Mumbai', 'Delhi', 'Delhi', 'Bangalore', 'Chennai']
}
df_inr = pd.DataFrame(raw_inr_data)
print("Raw INR Data Frame successfully initialized:")
df_inr

STEP 1: Simulating Raw Incoming INR Transaction Logs
Raw INR Data Frame successfully initialized:

  InvoiceID Amount_Raw  PaymentMode CustomerCity
0   INV-001     ₹1,500          UPI       Mumbai
1   INV-002    Rs. 450          upi        Delhi
2   INV-002    Rs. 450  Net Banking        Delhi
3   INV-004      ₹-200         Cash    Bangalore
4   INV-005     ₹3,200          NaN      Chennai

In [6]:
print("STEP 2: Structural Inspection Diagnostics")

print(f"Dataset Shape: {df_inr.shape}")
print(f"Duplicate Invoices Detected: {df_inr.duplicated(subset=['InvoiceID']).sum()}")
print("\nMissing Values Count:")
print(df_inr.isnull().sum())

STEP 2: Structural Inspection Diagnostics
Dataset Shape: (5, 4)
Duplicate Invoices Detected: 1

Missing Values Count:
InvoiceID       0
Amount_Raw      0
PaymentMode     1
CustomerCity    0
dtype: int64

In [9]:
print("STEP 3: Deduplication and Currency Normalization")

df_inr_clean = df_inr.drop_duplicates(subset=['InvoiceID'], keep='first').reset_index(drop=True)

df_inr_clean['Amount_INR'] = df_inr_clean['Amount_Raw'].str.replace('₹', '', regex=False)
df_inr_clean['Amount_INR'] = df_inr_clean['Amount_INR'].str.replace('Rs.', '', regex=False)
df_inr_clean['Amount_INR'] = df_inr_clean['Amount_INR'].str.replace(',', '', regex=False)
df_inr_clean['Amount_INR'] = df_inr_clean['Amount_INR'].str.strip()

df_inr_clean['Amount_INR'] = pd.to_numeric(df_inr_clean['Amount_INR'])

df_inr_clean[['InvoiceID', 'Amount_Raw', 'Amount_INR']]

STEP 3: Deduplication and Currency Normalization

  InvoiceID Amount_Raw  Amount_INR
0   INV-001     ₹1,500        1500
1   INV-002    Rs. 450         450
2   INV-004      ₹-200        -200
3   INV-005     ₹3,200        3200

In [12]:
print("STEP 4: Handling Anomalies, Missing Modes & Text Formatting")
df_inr_clean['PaymentMode'] = df_inr_clean['PaymentMode'].replace({'upi': 'UPI'})
frequent_mode = df_inr_clean['PaymentMode'].mode()[0]
df_inr_clean['PaymentMode'] = df_inr_clean['PaymentMode'].fillna(frequent_mode)

df_inr_clean['Amount_INR'] = df_inr_clean['Amount_INR'].abs()

df_inr_final = df_inr_clean.drop(columns=['Amount_Raw'])
print("Final Cleaned, Analysis-Ready INR Dataset:")
df_inr_final

STEP 4: Handling Anomalies, Missing Modes & Text Formatting
Final Cleaned, Analysis-Ready INR Dataset:

  InvoiceID PaymentMode CustomerCity  Amount_INR
0   INV-001         UPI       Mumbai        1500
1   INV-002         UPI        Delhi         450
2   INV-004        Cash    Bangalore         200
3   INV-005         UPI      Chennai        3200